hmrc/view-vat-returns-frontend

app/controllers/AuthorisedController.scala
app/controllers/VatReturnController.scala
app/views/yourVatReturn.scala.html
it/pages/VatReturnPageSpec.scala
it/stubs/AuthStub.scala
test/controllers/VatReturnControllerSpec.scala

*I meant component interface test and not integration test

BTAT-1222 Updated controller to receive VAT Return view

---

app/views/templates/userResearchBanner.scala.html
conf/messages
test/views/templates/UserResearchBannerSpec.scala

The rest of this subtask was done in an earlier PR after some confusion in the Jira ticket.

BTAT-1657 Added the 'no thanks' back to the banner

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/ReturnsController.scala
app/models/viewModels/VatReturnViewModel.scala
app/views/returns/completedReturns.scala.html
app/views/returns/returnDeadlines.scala.html
app/views/returns/vatReturnDetails.scala.html
conf/app.routes
conf/application.conf
conf/messages
it/pages/VatReturnDetailsPageSpec.scala
test/app/RouteSpec.scala
test/controllers/ReturnsControllerSpec.scala
test/mocks/MockAppConfig.scala
test/views/CompletedReturnsViewSpec.scala
test/views/VatReturnDetailsViewSpec.scala

Also updated 9 box return route to accept period key instead of start and end dates

Added extra route for 9 box return from payments page and added breadcrumb for page

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/MakePaymentController.scala
app/forms/MakePaymentForm.scala
app/models/payments/PaymentDetailsModel.scala
app/views/returns/vatReturnDetails.scala.html
conf/app.routes
conf/application.conf
test/controllers/ControllerBaseSpec.scala
test/controllers/MakePaymentControllerSpec.scala
test/mocks/MockAppConfig.scala
test/views/VatReturnDetailsViewSpec.scala

Btat 2307 - Add payments Handoff

---

app/connectors/VatApiConnector.scala
app/controllers/ReturnObligationsController.scala
app/models/VatReturnObligation.scala
app/services/ReturnsService.scala
it/connectors/VatApiConnectorISpec.scala
test/controllers/ReturnObligationsControllerSpec.scala
test/services/ReturnsServiceSpec.scala

Also removed duplicate Status object

Added custom json reads for return obligations

---

app/config/VatHeaderCarrierForPartialsConverter.scala
app/config/frontendAppConfig.scala
app/connectors/VatSubscriptionConnector.scala
app/controllers/feedback/FeedbackController.scala
app/views/feedback/feedback.scala.html
app/views/feedback/feedback_thankyou.scala.html
app/views/govuk_wrapper.scala.html
conf/app.routes
conf/messages
test/mocks/MockAppConfig.scala

To test locally start service: CONTACT_FRONTEND, DESKPRO_STUB and HMRCDESKPRO

BTAT-2015 - Implement Banner feedback  and set Beta Banner

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/ReturnsController.scala
app/models/viewModels/VatReturnViewModel.scala
app/views/returns/vatReturnDetails.scala.html
conf/application.conf
test/controllers/ReturnObligationsControllerSpec.scala
test/controllers/ReturnsControllerSpec.scala
test/views/VatReturnDetailsViewSpec.scala

Also changed post sign in redirect url to go to VAT homepage (agreed with design)
*Merge with app-config-base PR (see slack)*

Removed usages of LocalDate.now()

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/SignOutController.scala
app/views/errors/sessionTimeout.scala.html
app/views/errors/unauthorised.scala.html
app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/SignOutControllerSpec.scala
test/mocks/MockAppConfig.scala
test/views/errors/UnauthorisedViewSpec.scala

Also removed sign-out button on session-timeout page
Note: requires an app-config-base PR merged too

Updated content for unauthorised page

---

app/views/returns/vatReturnDetails.scala.html
app/views/templates/returns/paymentStatus.scala.html
conf/messages
test/controllers/ReturnsControllerSpec.scala
test/views/ReturnDeadlinesViewSpec.scala
test/views/VatReturnDetailsViewSpec.scala
test/views/templates/returns/PaymentStatusTemplateSpec.scala

Also slightly refactored ReturnsControllerSpec to remove duplicate code.

BTAT-2454 Updated content on Return Deadlines and 9-box pages

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/SignOutController.scala
app/views/govuk_wrapper.scala.html
conf/app.routes
conf/application.conf
test/controllers/SignOutControllerSpec.scala
test/mocks/MockAppConfig.scala

Can test locally by changing timeout settings in application.conf to short values e.g. period 20 and countdown 10

BTAT-2473 added timeout warning mechansism

---

app/config/ConfigKeys.scala
app/controllers/ReturnObligationsController.scala
app/services/ReturnsService.scala
app/views/returns/noUpcomingReturnDeadlines.scala.html
app/views/returns/returnDeadlines.scala.html
conf/messages
test/controllers/ReturnObligationsControllerSpec.scala
test/services/ReturnsServiceSpec.scala
test/views/NoUpcomingReturnDeadlinesViewSpec.scala
test/views/ReturnDeadlinesViewSpec.scala

Merge with acceptance tests branch for new test data to demo

Iterated return deadlines content to make extra call for fulfilled obs

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/MakePaymentController.scala
app/models/errors/ServiceError.scala
app/models/package.scala
app/services/PaymentsService.scala
app/views/errors/paymentsError.scala.html
conf/application.conf
conf/messages
test/controllers/MakePaymentControllerSpec.scala
test/mocks/MockAppConfig.scala
test/services/PaymentsServiceSpec.scala
test/views/errors/PaymentsErrorViewSpec.scala

**Merge this PR with this one please:**

BTAT-2642 Added graceful error handling for payments journey failures

---

app/controllers/ReturnsController.scala
test/controllers/MakePaymentControllerSpec.scala
test/controllers/ReturnsControllerSpec.scala

Increased test coverage for MakePaymentController and ReturnsController

---

app/audit/AuditingService.scala
app/config/ConfigKeys.scala
app/config/features/Features.scala
app/connectors/httpParsers/DirectDebitStatusHttpParser.scala
app/connectors/httpParsers/PaymentsHttpParser.scala
app/controllers/AuthorisedController.scala
app/controllers/ReturnsController.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/models/errors/apiErrors.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch.scala.html
app/views/returns/submittedReturns.scala.html
app/views/returns/vatReturnDetails.scala.html
conf/application.conf
conf/messages
it/connectors/VatObligationsConnectorISpec.scala
it/connectors/VatReturnsConnectorISpec.scala
it/pages/ReturnDeadlinesPageSpec.scala
it/pages/SubmittedReturnsPageSpec.scala
it/pages/VatReturnDetailsPageSpec.scala
it/stubs/VatObligationsStub.scala
it/stubs/VatReturnsStub.scala
test/config/features/FeaturesSpec.scala
test/controllers/ReturnsControllerSpec.scala
test/testOnly/controllers/FeatureSwitchControllerSpec.scala
test/views/SubmittedReturnsViewSpec.scala
test/views/VatReturnDetailsViewSpec.scala

Please merge these app-config PRs alongside this:

BTAT-3413 Remove redundant features

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch.scala.html

Please merge app config PRs first

Added submit return feature switch

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf

Here are the app config prs for this:

BTAT-6052 Added agent access feature switch

---

test/controllers/ControllerBaseSpec.scala
test/controllers/ReturnsControllerSpec.scala

[BTAT-6051] Added tests for agent access to nine box page

---

test/controllers/ControllerBaseSpec.scala
test/controllers/ReturnObligationsControllerSpec.scala

Do not merge. Needs to be merged after the following:

BTAT-6055 Added agent access for submitted returns page

---

app/controllers/ReturnObligationsController.scala
app/views/returns/optOutReturnDeadlines.scala.html
conf/messages
test/controllers/ReturnObligationsControllerSpec.scala
test/views/OptOutReturnDeadlinesViewSpec.scala

Added guidance for when return end date has not passed

---

app/controllers/ReturnsController.scala
app/views/errors/preMtdReturn.scala.html
build.sbt
conf/messages
conf/messages.cy
test/controllers/ReturnsControllerSpec.scala
test/views/errors/PreMtdReturnViewSpec.scala

Please do not merge this PR yet - waiting to hear from Helena (ETMP) about whether or not period key 9999 is a valid non-hybrid period key used for final returns and also if we should ever consider period keys which are hash and 3 numbers to be hybrid. 
My assumption in code for now is that it's only a hybrid return if there are 4 numbers.

BTAT-6613: Created view and logic for hybrid return error page

---

app/common/MandationStatuses.scala
app/controllers/AuthorisedController.scala
app/controllers/ReturnsController.scala
app/controllers/SubmittedReturnsController.scala
app/controllers/predicate/AuthoriseAgentWithClient.scala
build.sbt
test/controllers/predicates/AuthoriseAgentWithClientSpec.scala

This reverts commit 0bf6f8ed6161daecad5357055d5c69a6835ae444, reversing
changes made to c5177cf0bad174653715dfeb9cc1cace4b237047.

Revert "Merge remote-tracking branch 'origin/BTAT-6962'"

---

conf/application.conf

Merge along with the following:
- https://github.com/hmrc/app-config-base/pull/3263
- https://github.com/hmrc/app-config-staging/pull/4554

BTAT-7666 Replaced vat-vc-api-stub configuration

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/views/GovukWrapper.scala.html
app/views/MainTemplate.scala.html
conf/application.conf
test/mocks/MockAppConfig.scala

Please review together with https://github.com/hmrc/app-config-base/pull/4312

[BTAT-8488] Updating GTM

---

app/models/CustomerInformation.scala
build.sbt
test/controllers/ReturnDeadlinesControllerSpec.scala
test/controllers/ReturnsControllerSpec.scala
test/models/PaymentsSpec.scala

This can be reviewed but needs to be rebased once Sheila's branch has gone in

[BTAT-9969] - Increase test coverage for remaining files

---

app/controllers/AuthorisedController.scala
test/controllers/AuthorisedControllerSpec.scala
test/controllers/ControllerBaseSpec.scala

The current tests were passing after the refactor but I added two more tests for extra confidence that the updated code is exhibiting the correct behaviour.

BTAT-10109 Refactor to auth code to remove unreachable scenario

---

app/controllers/ReturnsController.scala
build.sbt
project/plugins.sbt
test/controllers/ReturnsControllerSpec.scala

Something to note with this task, firstly I'm not quite sure if this has been done correctly and secondly I haven't included any tests there weren't any to begin with, the coverage hasn't changed and after speaking with Paul it's quite a difficult thing to replicate locally.

[BTAT 10235] - Bug fix to account for delay for obligation data

---

app/controllers/ReturnsController.scala

I removed the logger message for the understood scenario of submission not processed yet, and combined the existing logger messages for return/obligation not found into one message further down the code.

Adjusted logger messages for VAT return page; reduced noise

---

build.sbt
project/plugins.sbt

[BTAT-10965] - Updated build.sbt with new bootstrap version to address scala upgrade issues

---

app/assets/stylesheets/application.scss
app/views/returns/OptOutReturnDeadlinesView.scala.html
app/views/returns/ReturnDeadlinesView.scala.html
app/views/returns/VatReturnDetailsView.scala.html
test/views/OptOutReturnDeadlinesViewSpec.scala
test/views/ReturnDeadlinesViewSpec.scala
test/views/VatReturnDetailsViewSpec.scala

Checked manually and ran validity, axe and wave to confirm no new issues were introduced.

BTAT-11262 use customised css to replace govuk-hint
